### ISSUE TITLE
gzip: drivers.tar.gz: not in gzip format

### ISSUE THREAD

**Issue by dmytro-dzyuba-nix** [hugolpz/Canon_printer#3]
sudo make -f ./install.mk BITS=64 PRINTER=LBP2900
gunzip -c drivers.tar.gz | tar xopf -

gzip: drivers.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
install.mk:36: recipe for target 'unzip' failed
make: *** [unzip] Error 2

**Comment by hugolpz** [comment]
This project is not maintaned (see [readme.md statment](https://github.com/hugolpz/Canon_printer/commit/73caa538e71a2350fa28fb09df134c5fdd939d71#diff-04c6e90faac2675aa89e2176d2eec7d8R37)).
