### ISSUE TITLE
Canon printer requires the driver to enable the connection between the product and a computer.

### ISSUE THREAD

**Issue by Varenaa** [hugolpz/Canon_printer#4]
Canon printer requires the driver to enable the connection between the product and a computer. But where I can found appropriate drivers for the Canon product. And what kind of situation can be happen if no suitable driver is available, How can I check the reason behind the issue [Canon Printer Not Responding](https://www.canonprintersupportnumbers.com/blog/fix-canon-printer-not-responding-error/) and compatibility of the product with the respective operating system?

**Comment by hugolpz** [comment]
[Warning: project is not maintained, but I will accept relevant pull request.]https://github.com/hugolpz/Canon_printer#notes)
